<?php

use Illuminate\Database\Seeder;

class CompaniesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('companies')->delete();
        
        \DB::table('companies')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'Richmond Surveying',
                'business_type_id' => 1,
                'tier_id' => 1,
                'main_company_id' => 1,
                'main_function_answer' => NULL,
                'photo_url' => 'https://app.buildlabour.com.au/storage/images/companies/2019/0926/91233/p_5R2C72isfRGV..png',
                'address' => '89593 Pagac Pass
North Maritzachester, OH 15572-2999',
                'phone' => '623374051',
                'introduction' => 'We are a modern, professional and sophisticated surveying firm specialising in land development, construction and engineering surveying. We provide quality, cost-effective and efficient surveying service.',
                'website' => 'friesen.com',
                'operate_outside_states' => 0,
                'states' => NULL,
                'created_by' => 2,
                'locations_json' => '["2933 Hills Greens, South Nicola, AK 03297"]',
                'created_at' => '2019-09-26 06:27:24',
                'updated_at' => '2019-12-19 04:39:55',
                'deleted_at' => '2019-12-19 04:39:55',
            ),
            1 => 
            array (
                'id' => 7,
                'name' => 'The Tempo Group',
                'business_type_id' => 1,
                'tier_id' => 4,
                'main_company_id' => 1,
                'main_function_answer' => NULL,
                'photo_url' => 'http://178.128.217.88/storage/images/companies/2019/1011/91347/p_zKGSXnxlJTJO..png',
                'address' => '28 Diane Street Mornington VIC',
                'phone' => '03 5976 3629',
                'introduction' => 'Tempo Development Group is 10 years old and is a fully licenced domestic and commercial building company operating throughout Victoria.',
                'website' => 'https://thetempogroup.com.au',
                'operate_outside_states' => 0,
                'states' => NULL,
                'created_by' => 21,
                'locations_json' => NULL,
                'created_at' => '2019-10-11 10:40:53',
                'updated_at' => '2020-06-25 23:16:31',
                'deleted_at' => '2020-06-25 23:16:31',
            ),
            2 => 
            array (
                'id' => 8,
                'name' => 'Warwick Constructions',
                'business_type_id' => 1,
                'tier_id' => 4,
                'main_company_id' => 1,
                'main_function_answer' => NULL,
                'photo_url' => 'http://178.128.217.88/storage/images/companies/2019/1011/91366/p_nSD3aD2zRZLJ..png',
                'address' => '1/22 Council Street, Hawthorn East, VIC, 3123',
                'phone' => '03 9939 3949',
                'introduction' => NULL,
                'website' => 'https://www.warwickconstructions.com.au/',
                'operate_outside_states' => 0,
                'states' => NULL,
                'created_by' => 22,
                'locations_json' => NULL,
                'created_at' => '2019-10-11 11:49:24',
                'updated_at' => '2020-06-26 03:38:59',
                'deleted_at' => '2020-06-26 03:38:59',
            ),
            3 => 
            array (
                'id' => 10,
                'name' => 'Policrete',
                'business_type_id' => 1,
                'tier_id' => 2,
                'main_company_id' => 2,
                'main_function_answer' => 'Concreting',
                'photo_url' => 'https://app.buildlabour.com.au/storage/images/companies/2019/1014/91404/p_dsp6RKwKOa0J..png',
                'address' => '11 Geelong St, West Footscray',
                'phone' => '1800 289 308',
                'introduction' => 'Melbourne’s
full-service, pour-and-polish concrete
flooring specialists. We deliver long-lasting, low-maintenance, good-looking floors for homes, retail outlets, warehouses and
workshops.',
                'website' => 'https://www.policrete.com.au',
                'operate_outside_states' => 1,
                'states' => 'QLD,NSW,SA,VIC,NT,TAS,ACT,WA',
                'created_by' => 28,
                'locations_json' => NULL,
                'created_at' => '2019-10-14 11:10:38',
                'updated_at' => '2020-06-04 23:49:23',
                'deleted_at' => '2020-06-04 23:49:23',
            ),
            4 => 
            array (
                'id' => 11,
                'name' => 'Moon Building Group',
                'business_type_id' => 1,
                'tier_id' => 4,
                'main_company_id' => 1,
                'main_function_answer' => NULL,
                'photo_url' => 'https://app.buildlabour.com.au/storage/images/companies/2019/1014/91423/p_Vck2Xmmg2Y9s..png',
                'address' => '9 Taylor St, Thornbury',
                'phone' => '0430 090 211',
                'introduction' => 'At Moon Building Group, our approach to construction comes from an appreciation and respect for excellent architecture. It’s this attitude that drives us to breathe life into some of Melbourne’s most stunning designs; to transfer their beauty from blueprint to reality.

From jaw dropping facades, to interiors completed with finesse, you can trust us with your most intricate architectural concepts. Contact us today!',
                'website' => 'https://www.moonbg.com.au/',
                'operate_outside_states' => 0,
                'states' => NULL,
                'created_by' => 29,
                'locations_json' => NULL,
                'created_at' => '2019-10-14 12:23:37',
                'updated_at' => '2020-06-26 03:38:34',
                'deleted_at' => '2020-06-26 03:38:34',
            ),
            5 => 
            array (
                'id' => 12,
                'name' => 'dPP Hydronics',
                'business_type_id' => 1,
                'tier_id' => 3,
                'main_company_id' => 2,
                'main_function_answer' => 'Heating Specialist, In Slab Heating & Boiler Servicing',
                'photo_url' => 'https://app.buildlabour.com.au/storage/images/companies/2019/1014/91442/p_pDqgqGGdY9nr..png',
                'address' => '18 De Havilland Rd, Mordialloc VIC',
                'phone' => '1300 303 471',
                'introduction' => 'dPP Hydronic Heating offer an industry-leading 30 year warranty on all underfloor heating systems*.

dPP Hydronic Heating is the preferred hydronic heating installers by many of Australia\'s top Architects and Builders. dPP brings many years of experience in designing, installing and servicing hydronic heating systems. We specialise in-slab heating and radiator panels in new builds, renovations and existing homes. Contact us today for advice or costing.',
                'website' => 'https://dpphydronics.com.au',
                'operate_outside_states' => 1,
                'states' => 'VIC,NSW',
                'created_by' => 30,
                'locations_json' => NULL,
                'created_at' => '2019-10-14 12:42:49',
                'updated_at' => '2019-10-14 12:47:57',
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id' => 13,
                'name' => 'Rawlinson Constructions',
                'business_type_id' => 1,
                'tier_id' => 4,
                'main_company_id' => 2,
                'main_function_answer' => 'Carpentry',
                'photo_url' => 'https://app.buildlabour.com.au/storage/images/companies/2019/1014/91461/p_dtl8oF1pe45m..png',
                'address' => '15 Pearse rd, Blairgowrie',
                'phone' => '0404885691',
                'introduction' => 'We are a carpentry crew based on the Mornington Peninsula, we work from Melbourne to Sorrento. 

Majority of our work is high end residential.',
                'website' => NULL,
                'operate_outside_states' => 0,
                'states' => NULL,
                'created_by' => 31,
                'locations_json' => NULL,
                'created_at' => '2019-10-14 14:33:28',
                'updated_at' => '2020-05-25 03:19:24',
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'id' => 14,
                'name' => 'Mick Royle Plastering',
                'business_type_id' => 1,
                'tier_id' => 4,
                'main_company_id' => 2,
                'main_function_answer' => 'Plastering Specialist',
                'photo_url' => 'https://app.buildlabour.com.au/storage/images/companies/2019/1015/91480/p_WdLZPwBmSodc..png',
                'address' => 'Mornington, Victoria, Australia',
                'phone' => '0413302633',
                'introduction' => 'Plastering Specialist operating in the high end residential space for the last 20 years',
                'website' => 'www.mickrolyle.com.au',
                'operate_outside_states' => 0,
                'states' => NULL,
                'created_by' => 32,
                'locations_json' => NULL,
                'created_at' => '2019-10-15 01:45:35',
                'updated_at' => '2019-10-15 01:47:22',
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 15,
                'name' => 'Prolifica Building Co.',
                'business_type_id' => 1,
                'tier_id' => 4,
                'main_company_id' => 1,
                'main_function_answer' => NULL,
                'photo_url' => 'https://app.buildlabour.com.au/storage/images/companies/2019/1015/91499/p_QrgOQfoY85lh..png',
                'address' => '52A St Kilda Rd, St Kilda VIC 3182',
            'phone' => '(03) 9505 0108',
                'introduction' => 'We believe that collaborative thinking, considered design and a positive building experience can change your living for the better. Whatever the challenge, we have the dedication and the energy to create a space that lives up to your vision.',
                'website' => 'https://www.prolificabuilding.com/',
                'operate_outside_states' => 0,
                'states' => NULL,
                'created_by' => 33,
                'locations_json' => NULL,
                'created_at' => '2019-10-15 01:51:51',
                'updated_at' => '2019-10-15 01:52:24',
                'deleted_at' => NULL,
            ),
            9 => 
            array (
                'id' => 16,
                'name' => 'Select Plumbing',
                'business_type_id' => 1,
                'tier_id' => 3,
                'main_company_id' => 2,
                'main_function_answer' => NULL,
                'photo_url' => 'https://app.buildlabour.com.au/storage/images/companies/2019/1015/91518/p_qmL3VAS3BAmk..png',
                'address' => 'PO BOX 1105 MOUNTAIN GATE VIC',
                'phone' => '0488 285 273',
                'introduction' => NULL,
                'website' => 'www.selectplumb.com',
                'operate_outside_states' => 0,
                'states' => NULL,
                'created_by' => 34,
                'locations_json' => NULL,
                'created_at' => '2019-10-15 02:03:44',
                'updated_at' => '2019-10-15 02:03:44',
                'deleted_at' => NULL,
            ),
            10 => 
            array (
                'id' => 17,
                'name' => 'Probuild',
                'business_type_id' => 2,
                'tier_id' => 1,
                'main_company_id' => 1,
                'main_function_answer' => NULL,
                'photo_url' => 'https://app.buildlabour.com.au/storage/images/companies/2019/1017/91537/p_huzbSgy76cK8..png',
                'address' => 'Level 10, 580 St Kilda Road MELBOURNE VIC 3004',
                'phone' => '03 9693 8222',
                'introduction' => NULL,
                'website' => 'https://www.probuild.com.au/',
                'operate_outside_states' => 1,
                'states' => 'QLD,WA,NSW,ACT,VIC',
                'created_by' => 166,
                'locations_json' => NULL,
                'created_at' => '2019-10-17 07:25:41',
                'updated_at' => '2019-10-17 07:25:41',
                'deleted_at' => NULL,
            ),
            11 => 
            array (
                'id' => 19,
                'name' => 'Peninsula Stone Masons',
                'business_type_id' => 1,
                'tier_id' => 4,
                'main_company_id' => 2,
                'main_function_answer' => 'Stonemason',
                'photo_url' => 'https://app.buildlabour.com.au/storage/images/companies/2019/1018/91575/p_XeXuiDgHhdJx..png',
                'address' => 'ABBOTSFORD VIC',
                'phone' => '0418 357 650',
                'introduction' => NULL,
                'website' => 'http://peninsulastonemasons.com/',
                'operate_outside_states' => 1,
                'states' => 'NSW,SA',
                'created_by' => 225,
                'locations_json' => NULL,
                'created_at' => '2019-10-18 02:10:19',
                'updated_at' => '2019-10-18 02:10:19',
                'deleted_at' => NULL,
            ),
            12 => 
            array (
                'id' => 20,
                'name' => 'ERNI Dev Ph',
                'business_type_id' => 1,
                'tier_id' => 4,
                'main_company_id' => 4,
                'main_function_answer' => NULL,
                'photo_url' => 'https://178.128.217.88/storage/images/companies/2019/1119/91594/p_x8Wm0dQwB28i..png',
                'address' => 'Switzerland Road, Ghin Ghin, 3717, Victoria',
                'phone' => '1234566790',
                'introduction' => NULL,
                'website' => 'websitesample.com.ph',
                'operate_outside_states' => 1,
                'states' => 'NSW,ACT,TAS',
                'created_by' => 277,
                'locations_json' => NULL,
                'created_at' => '2019-11-19 09:28:09',
                'updated_at' => '2020-01-02 08:00:00',
                'deleted_at' => '2020-01-02 08:00:00',
            ),
            13 => 
            array (
                'id' => 21,
                'name' => 'Test Company',
                'business_type_id' => 2,
                'tier_id' => 2,
                'main_company_id' => 1,
                'main_function_answer' => NULL,
                'photo_url' => NULL,
                'address' => 'Sydney Seaplanes, Rose Bay, 2029, Sydney, New South Wales',
                'phone' => '8989787888',
                'introduction' => NULL,
                'website' => 'testtest007.com',
                'operate_outside_states' => 1,
                'states' => 'NSW,QLD,WA,TAS,SA,VIC,NT,ACT',
                'created_by' => 279,
                'locations_json' => NULL,
                'created_at' => '2019-11-19 13:34:00',
                'updated_at' => '2019-12-19 04:39:56',
                'deleted_at' => '2019-12-19 04:39:56',
            ),
            14 => 
            array (
                'id' => 22,
                'name' => 'Appetiser Test Company',
                'business_type_id' => 1,
                'tier_id' => 1,
                'main_company_id' => 2,
                'main_function_answer' => 'Heating Specialist',
                'photo_url' => NULL,
            'address' => 'Sydney Airport (SYD), Mascot, 2020, Sydney, New South Wales',
                'phone' => '5555555555fdsfdsfdsfdsf5454545',
                'introduction' => NULL,
                'website' => NULL,
                'operate_outside_states' => 0,
                'states' => NULL,
                'created_by' => 280,
                'locations_json' => NULL,
                'created_at' => '2019-11-19 17:48:30',
                'updated_at' => '2019-12-19 04:40:09',
                'deleted_at' => '2019-12-19 04:40:09',
            ),
            15 => 
            array (
                'id' => 23,
                'name' => 'Test Company SS',
                'business_type_id' => 1,
                'tier_id' => 3,
                'main_company_id' => 1,
                'main_function_answer' => NULL,
                'photo_url' => NULL,
                'address' => 'Test Address',
                'phone' => '1234567890',
                'introduction' => NULL,
                'website' => 'www.testss.com',
                'operate_outside_states' => 0,
                'states' => NULL,
                'created_by' => 286,
                'locations_json' => NULL,
                'created_at' => '2019-11-20 08:09:49',
                'updated_at' => '2019-12-19 04:40:09',
                'deleted_at' => '2019-12-19 04:40:09',
            ),
            16 => 
            array (
                'id' => 24,
                'name' => 'Dreamtesting',
                'business_type_id' => 4,
                'tier_id' => 4,
                'main_company_id' => 2,
                'main_function_answer' => 'construction',
                'photo_url' => 'https://app.buildlabour.com.au/storage/images/companies/2019/1120/91670/p_fRpabVQ8UTbC..png',
                'address' => 'Malbeling Close, Hillman, 6168, Perth, Western Australia',
                'phone' => '1234445555',
                'introduction' => NULL,
                'website' => 'www.test.com',
                'operate_outside_states' => 1,
                'states' => 'QLD,WA,ACT,NSW,SA,TAS,NT,VIC',
                'created_by' => 291,
                'locations_json' => NULL,
                'created_at' => '2019-11-20 20:07:03',
                'updated_at' => '2019-12-19 04:40:09',
                'deleted_at' => '2019-12-19 04:40:09',
            ),
            17 => 
            array (
                'id' => 25,
                'name' => 'new',
                'business_type_id' => 1,
                'tier_id' => 1,
                'main_company_id' => 1,
                'main_function_answer' => NULL,
                'photo_url' => NULL,
                'address' => 'Qwerk, Wilston, 4051, Brisbane, Queensland',
                'phone' => '9898989898',
                'introduction' => NULL,
                'website' => NULL,
                'operate_outside_states' => 0,
                'states' => NULL,
                'created_by' => 294,
                'locations_json' => NULL,
                'created_at' => '2019-11-21 15:25:32',
                'updated_at' => '2020-01-02 07:59:55',
                'deleted_at' => '2020-01-02 07:59:55',
            ),
            18 => 
            array (
                'id' => 26,
                'name' => 'Google',
                'business_type_id' => 2,
                'tier_id' => 3,
                'main_company_id' => 4,
                'main_function_answer' => 'Web Design',
                'photo_url' => 'https://app.buildlabour.com.au/storage/images/companies/2019/1126/91708/p_1nmB2sG19mAP..png',
                'address' => 'Sydney Seaplanes, Rose Bay, 2029, Sydney, New South Wales',
                'phone' => '1234567890',
                'introduction' => NULL,
                'website' => 'http://google.com',
                'operate_outside_states' => 0,
                'states' => NULL,
                'created_by' => 297,
                'locations_json' => NULL,
                'created_at' => '2019-11-26 10:34:28',
                'updated_at' => '2020-01-02 07:59:49',
                'deleted_at' => '2020-01-02 07:59:49',
            ),
            19 => 
            array (
                'id' => 27,
                'name' => 'Raybird Designs',
                'business_type_id' => NULL,
                'tier_id' => NULL,
                'main_company_id' => 1,
                'main_function_answer' => NULL,
                'photo_url' => 'https://app.buildlabour.com.au/storage/images/companies/2019/1218/91727/p_lOU2CUwWXlTw..png',
                'address' => 'Harrington Drive, Narre Warren South, 3805, Melbourne, Victoria',
                'phone' => '0423289529',
                'introduction' => NULL,
                'website' => 'https://raybirddesigns.com.au',
                'operate_outside_states' => 0,
                'states' => NULL,
                'created_by' => 305,
                'locations_json' => NULL,
                'created_at' => '2019-12-18 06:36:31',
                'updated_at' => '2019-12-18 06:36:32',
                'deleted_at' => NULL,
            ),
            20 => 
            array (
                'id' => 28,
                'name' => 'Appetiser Test Company',
                'business_type_id' => 1,
                'tier_id' => 2,
                'main_company_id' => 1,
                'main_function_answer' => NULL,
                'photo_url' => 'https://app.buildlabour.com.au/storage/images/companies/2020/0107/91746/p_4QYLAC0UFulS..png',
                'address' => 'Melbourne, Victoria',
                'phone' => '3272223555',
                'introduction' => NULL,
                'website' => NULL,
                'operate_outside_states' => 0,
                'states' => NULL,
                'created_by' => 306,
                'locations_json' => NULL,
                'created_at' => '2020-01-07 18:05:04',
                'updated_at' => '2020-02-10 08:29:29',
                'deleted_at' => '2020-02-10 08:29:29',
            ),
            21 => 
            array (
                'id' => 29,
                'name' => 'asdasdas',
                'business_type_id' => 3,
                'tier_id' => 2,
                'main_company_id' => 1,
                'main_function_answer' => NULL,
                'photo_url' => NULL,
                'address' => 'Narre Warren Station, Narre Warren, 3805, Melbourne, Victoria',
                'phone' => '1234123412',
                'introduction' => NULL,
                'website' => 'http://w.com',
                'operate_outside_states' => 0,
                'states' => NULL,
                'created_by' => 310,
                'locations_json' => NULL,
                'created_at' => '2020-02-06 01:03:51',
                'updated_at' => '2020-02-10 08:29:34',
                'deleted_at' => '2020-02-10 08:29:34',
            ),
            22 => 
            array (
                'id' => 30,
                'name' => 'Sinjen',
                'business_type_id' => 1,
                'tier_id' => 4,
                'main_company_id' => 1,
                'main_function_answer' => NULL,
                'photo_url' => 'https://app.buildlabour.com.au/storage/images/companies/2020/0220/91784/p_3LD8RbpBVqvZ..png',
                'address' => '14 Risley Street, Richmond Victoria 3121, Australia',
                'phone' => '0394212036',
                'introduction' => 'Sinjen is a premium architectural building company based in Richmond, Melbourne. We specialise in building unique, innovative and high-impact design projects.',
                'website' => 'http://www.sinjen.com.au/',
                'operate_outside_states' => 0,
                'states' => NULL,
                'created_by' => 368,
                'locations_json' => NULL,
                'created_at' => '2020-02-20 12:34:02',
                'updated_at' => '2020-02-20 13:07:36',
                'deleted_at' => NULL,
            ),
            23 => 
            array (
                'id' => 31,
                'name' => 'National Concrete Solutions Australia',
                'business_type_id' => 3,
                'tier_id' => 1,
                'main_company_id' => 2,
                'main_function_answer' => 'Concrete Repair and Remediation',
                'photo_url' => 'https://app.buildlabour.com.au/storage/images/companies/2020/0222/91803/p_NhAHclYeduhs..png',
                'address' => 'Atlantic Drive, Keysborough Victoria 3173, Australia',
                'phone' => '0395455283',
                'introduction' => NULL,
                'website' => 'https://ncsaustralia.com.au/',
                'operate_outside_states' => 1,
                'states' => 'QLD,NSW,SA,VIC,NT,ACT,WA',
                'created_by' => 387,
                'locations_json' => NULL,
                'created_at' => '2020-02-22 00:57:12',
                'updated_at' => '2020-02-22 00:57:43',
                'deleted_at' => NULL,
            ),
            24 => 
            array (
                'id' => 32,
                'name' => 'Earth Structures Peninsula',
                'business_type_id' => 1,
                'tier_id' => 1,
                'main_company_id' => 1,
                'main_function_answer' => NULL,
                'photo_url' => NULL,
                'address' => 'Melbourne, Victoria, Australia',
                'phone' => '0458723594',
            'introduction' => 'The Earth Structures Group (earthstructuresgroup.com.au) specialises in the construction of stabilised rammed earth walls.',
                'website' => 'earthstructuresgroup.com.au',
                'operate_outside_states' => 1,
                'states' => 'NSW',
                'created_by' => 442,
                'locations_json' => NULL,
                'created_at' => '2020-02-27 04:17:25',
                'updated_at' => '2020-02-27 04:52:48',
                'deleted_at' => NULL,
            ),
            25 => 
            array (
                'id' => 33,
                'name' => 'IZI Constructions',
                'business_type_id' => 2,
                'tier_id' => 1,
                'main_company_id' => 1,
                'main_function_answer' => NULL,
                'photo_url' => NULL,
                'address' => '7 Edwin Street, Mortlake New South Wales 2137, Australia',
                'phone' => '0418414771',
                'introduction' => NULL,
                'website' => NULL,
                'operate_outside_states' => 0,
                'states' => NULL,
                'created_by' => 522,
                'locations_json' => NULL,
                'created_at' => '2020-03-11 11:55:52',
                'updated_at' => '2020-03-11 11:55:52',
                'deleted_at' => NULL,
            ),
            26 => 
            array (
                'id' => 34,
                'name' => 'Build Labour',
                'business_type_id' => 2,
                'tier_id' => 2,
                'main_company_id' => 2,
                'main_function_answer' => 'Labour Hire',
                'photo_url' => 'https://app.buildlabour.com.au/storage/images/companies/2020/0430/91860/p_fiGrZ5vKgJVz..png',
                'address' => '7/ 4 Lansdowne Road, St Kilda East',
                'phone' => '0457001197',
                'introduction' => NULL,
                'website' => 'https://www.buildlabour.com.au/',
                'operate_outside_states' => 1,
                'states' => 'QLD,NSW,SA,VIC',
                'created_by' => 590,
                'locations_json' => NULL,
                'created_at' => '2020-04-30 03:05:28',
                'updated_at' => '2020-04-30 03:05:28',
                'deleted_at' => NULL,
            ),
            27 => 
            array (
                'id' => 35,
                'name' => 'Test',
                'business_type_id' => 1,
                'tier_id' => 1,
                'main_company_id' => 1,
                'main_function_answer' => NULL,
                'photo_url' => NULL,
                'address' => '12 Steet Street, Footscray Victoria 3011, Australia',
                'phone' => '0400000000',
                'introduction' => NULL,
                'website' => 'www.website.com',
                'operate_outside_states' => 0,
                'states' => NULL,
                'created_by' => 594,
                'locations_json' => NULL,
                'created_at' => '2020-05-12 22:22:28',
                'updated_at' => '2020-06-25 23:16:44',
                'deleted_at' => '2020-06-25 23:16:44',
            ),
            28 => 
            array (
                'id' => 36,
                'name' => 'Builders Academy',
                'business_type_id' => 1,
                'tier_id' => 1,
                'main_company_id' => 5,
                'main_function_answer' => 'Vocational',
                'photo_url' => 'https://app.buildlabour.com.au/storage/images/companies/2020/0513/91898/p_vS62tvFgApAa..png',
                'address' => 'Level 4, 570 St. Kilda Rd, Melbourne, VIC 3004',
                'phone' => '1300534363',
                'introduction' => NULL,
                'website' => 'https://buildersacademy.com.au/',
                'operate_outside_states' => 1,
                'states' => 'QLD,WA,ACT,NSW,TAS,SA,VIC,NT',
                'created_by' => 595,
                'locations_json' => NULL,
                'created_at' => '2020-05-13 01:36:29',
                'updated_at' => '2020-06-25 23:16:57',
                'deleted_at' => '2020-06-25 23:16:57',
            ),
            29 => 
            array (
                'id' => 37,
                'name' => 'JMW Masonry',
                'business_type_id' => 2,
                'tier_id' => 3,
                'main_company_id' => 2,
                'main_function_answer' => 'Brick & Blocklayer',
                'photo_url' => 'http://app.buildlabour.com.au/storage/images/companies/2020/0525/91917/p_qvH8Mt0UGrb0..png',
                'address' => 'Mornington, Victoria, Australia',
                'phone' => '0458091394',
                'introduction' => 'High end residential and commercial brick and blocklaying.
Servicing the mornington peninsula and bayside areas.',
                'website' => NULL,
                'operate_outside_states' => 0,
                'states' => NULL,
                'created_by' => 600,
                'locations_json' => NULL,
                'created_at' => '2020-05-25 02:02:43',
                'updated_at' => '2020-06-04 07:16:30',
                'deleted_at' => NULL,
            ),
            30 => 
            array (
                'id' => 38,
                'name' => 'Fm One Industries',
                'business_type_id' => 2,
                'tier_id' => 2,
                'main_company_id' => 1,
                'main_function_answer' => NULL,
                'photo_url' => 'https://app.buildlabour.com.au/storage/images/companies/2020/0601/91936/p_IFLudoygvRof..png',
                'address' => '72 Hambidge Crescent, Chisholm Australian Capital Territory 2905, Australia',
                'phone' => '0447647785',
                'introduction' => NULL,
                'website' => NULL,
                'operate_outside_states' => 1,
                'states' => 'NSW,ACT',
                'created_by' => 606,
                'locations_json' => NULL,
                'created_at' => '2020-06-01 12:34:39',
                'updated_at' => '2020-06-01 12:34:39',
                'deleted_at' => NULL,
            ),
            31 => 
            array (
                'id' => 39,
                'name' => 'Earth Structures Peninsula',
                'business_type_id' => 1,
                'tier_id' => 4,
                'main_company_id' => 2,
                'main_function_answer' => 'Rammed Earth',
                'photo_url' => 'https://app.buildlabour.com.au/storage/images/companies/2020/0604/91955/p_OMcWxYS5qfbD..png',
                'address' => 'Mornington, Victoria, Australia',
                'phone' => '0412756755',
                'introduction' => 'Earth Structures Group specialises in the construction of rammed earth walls. It\'s what we do, and we do it really well...

Over the past 30 years, contemporary rammed earth walls have become a much loved building material for Australian architects who understand its unique thermal and aesthetic benefits.',
                'website' => 'www.earthstructuresgroup.com.au',
                'operate_outside_states' => 1,
                'states' => 'SA,NSW',
                'created_by' => 611,
                'locations_json' => NULL,
                'created_at' => '2020-06-04 23:16:59',
                'updated_at' => '2020-06-04 23:32:06',
                'deleted_at' => NULL,
            ),
            32 => 
            array (
                'id' => 40,
                'name' => 'Policrete',
                'business_type_id' => 1,
                'tier_id' => 4,
                'main_company_id' => 2,
                'main_function_answer' => 'Polished Concrete',
                'photo_url' => 'https://app.buildlabour.com.au/storage/images/companies/2020/0604/91974/p_9Q6Whyc6Egkf..png',
                'address' => 'Melbourne, Victoria, Australia',
                'phone' => '0401665588',
                'introduction' => 'Melbourne’s full-service, pour-and-polish concrete
flooring specialists. We deliver long-lasting, low-maintenance, good-looking floors for homes, retail outlets, warehouses and
workshops.',
                'website' => NULL,
                'operate_outside_states' => 0,
                'states' => NULL,
                'created_by' => 612,
                'locations_json' => NULL,
                'created_at' => '2020-06-04 23:53:35',
                'updated_at' => '2020-06-04 23:57:55',
                'deleted_at' => NULL,
            ),
            33 => 
            array (
                'id' => 41,
                'name' => 'Pro-Pin Professional Underpinning',
                'business_type_id' => 1,
                'tier_id' => 3,
                'main_company_id' => 1,
                'main_function_answer' => NULL,
                'photo_url' => 'https://app.buildlabour.com.au/storage/images/companies/2020/0618/91993/p_PemrcUvvanT8..png',
                'address' => '2 Forest Track, Kallista Victoria 3791, Australia',
                'phone' => '0408035419',
                'introduction' => 'We are a family owned and run business specialising in underpinning across all suburbs of Melbourne.
We pride ourselves on offering a professional service to all of our customers.',
                'website' => 'www.pro-pin.com.au',
                'operate_outside_states' => 0,
                'states' => NULL,
                'created_by' => 678,
                'locations_json' => NULL,
                'created_at' => '2020-06-18 09:42:06',
                'updated_at' => '2020-06-19 08:13:43',
                'deleted_at' => NULL,
            ),
            34 => 
            array (
                'id' => 42,
                'name' => 'Offbite Projects',
                'business_type_id' => 2,
                'tier_id' => 3,
                'main_company_id' => 1,
                'main_function_answer' => NULL,
                'photo_url' => NULL,
                'address' => '24 Clifton Street, Prahran Victoria 3181, Australia',
                'phone' => '0418325058',
                'introduction' => NULL,
                'website' => 'www.offbite.net.au',
                'operate_outside_states' => 0,
                'states' => NULL,
                'created_by' => 698,
                'locations_json' => NULL,
                'created_at' => '2020-06-24 07:50:23',
                'updated_at' => '2020-06-24 07:50:23',
                'deleted_at' => NULL,
            ),
            35 => 
            array (
                'id' => 43,
                'name' => 'The Tempo Group',
                'business_type_id' => 2,
                'tier_id' => 2,
                'main_company_id' => 1,
                'main_function_answer' => NULL,
                'photo_url' => 'https://app.buildlabour.com.au/storage/images/companies/2020/0625/92031/p_3YY7YXuQdpha..png',
                'address' => '28 Diane St, Mornington VIC 3931',
                'phone' => '0359763629',
                'introduction' => NULL,
                'website' => 'thetempogroup.com.au',
                'operate_outside_states' => 0,
                'states' => NULL,
                'created_by' => 708,
                'locations_json' => NULL,
                'created_at' => '2020-06-25 23:29:54',
                'updated_at' => '2020-06-25 23:29:54',
                'deleted_at' => NULL,
            ),
            36 => 
            array (
                'id' => 44,
                'name' => 'Rawlinson Constructions',
                'business_type_id' => 1,
                'tier_id' => 1,
                'main_company_id' => 1,
                'main_function_answer' => NULL,
                'photo_url' => 'https://app.buildlabour.com.au/storage/images/companies/2020/0626/92050/p_1uF4GLDFzDTU..png',
                'address' => 'Rye, Victoria, Australia',
                'phone' => '0412345678',
                'introduction' => NULL,
                'website' => NULL,
                'operate_outside_states' => 0,
                'states' => NULL,
                'created_by' => 710,
                'locations_json' => NULL,
                'created_at' => '2020-06-26 04:07:31',
                'updated_at' => '2020-06-26 04:07:31',
                'deleted_at' => NULL,
            ),
            37 => 
            array (
                'id' => 46,
                'name' => 'asdasd',
                'business_type_id' => NULL,
                'tier_id' => NULL,
                'main_company_id' => 2,
                'main_function_answer' => NULL,
                'photo_url' => NULL,
                'address' => '49 harrington drtive',
                'phone' => '1231231231',
                'introduction' => NULL,
                'website' => NULL,
                'operate_outside_states' => 0,
                'states' => NULL,
                'created_by' => 759,
                'locations_json' => NULL,
                'created_at' => '2020-07-06 02:38:21',
                'updated_at' => '2020-07-06 02:55:40',
                'deleted_at' => '2020-07-06 02:55:40',
            ),
            38 => 
            array (
                'id' => 47,
                'name' => 'Wilkinson Builders',
                'business_type_id' => 1,
                'tier_id' => 4,
                'main_company_id' => 1,
                'main_function_answer' => NULL,
                'photo_url' => NULL,
                'address' => '103 Kars Street, Frankston South Victoria 3199, Australia',
                'phone' => '0413511767',
                'introduction' => NULL,
                'website' => NULL,
                'operate_outside_states' => 0,
                'states' => NULL,
                'created_by' => 844,
                'locations_json' => NULL,
                'created_at' => '2020-07-23 00:45:32',
                'updated_at' => '2020-07-23 00:45:32',
                'deleted_at' => NULL,
            ),
        ));
        
        
    }
}